version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    command: >
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres-bach:
    image: postgres:16
    container_name: postgres_bach
    restart: unless-stopped
    environment:
      POSTGRES_DB: bachdb        # Nome do banco para o Spring Batch
      POSTGRES_USER: bachuser
      POSTGRES_PASSWORD: bachpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_bach_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres_bach_data:
