spring:
  application:
    name: Treinamento Spring Batch

  datasource:
    mysql-datasource:
      jdbc-url: jdbc:mysql://localhost:3306/appdb
      username: appuser
      password: apppass
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-timeout: 30000

    postgres-datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/bachdb
      username: bachuser
      password: bachpass
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-timeout: 30000

  batch:
    jdbc:
      initialize-schema: never   # cria as tabelas do Batch no postgres
